default:
  tags:
    - docker
image:
  name: docker:28
services:
  - docker:dind

before_script:
  - echo "$REGISTRY_PASSWORD" | docker login $CONTAINER_REGISTRY -u $REGISTRY_USER --password-stdin

stages:
  - build

variables:
  CONTAINER_REGISTRY: registrywp.wvservices.com
  PROJECT_NAMESPACE: waves

build-and-push:
  stage: build
  parallel:
    matrix:
      - IMAGE_NAME: [nodemon, nodemon-telegram, nodemon-discord]
  only:
    - tags
  script: |-
    docker build -t $CONTAINER_REGISTRY/$PROJECT_NAMESPACE/$IMAGE_NAME:$CI_COMMIT_REF_NAME \
                 -t $CONTAINER_REGISTRY/$PROJECT_NAMESPACE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA \
                 -t $CONTAINER_REGISTRY/$PROJECT_NAMESPACE/$IMAGE_NAME:latest . \
                 -f Dockerfile-$IMAGE_NAME
    docker push $CONTAINER_REGISTRY/$PROJECT_NAMESPACE/$IMAGE_NAME:$CI_COMMIT_REF_NAME
    docker push $CONTAINER_REGISTRY/$PROJECT_NAMESPACE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    docker push $CONTAINER_REGISTRY/$PROJECT_NAMESPACE/$IMAGE_NAME:latest
