default:
  tags:
    - docker
image:
  name: amazon/aws-cli
  entrypoint: [""]
services:
  - docker:dind

before_script:
  - amazon-linux-extras install docker
  - aws --version
  - docker --version
  - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $CONTAINER_REGISTRY

stages:
  - build

variables:
  CONTAINER_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

build-and-push:
  stage: build
  parallel:
    matrix:
      - IMAGE_NAME: [nodemon, nodemon-telegram, nodemon-discord]
  script: |-
    docker build -t $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$IMAGE_NAME:CI_COMMIT_REF_NAME -t $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$IMAGE_NAME:latest . -f Dockerfile-$IMAGE_NAME
    docker push $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$IMAGE_NAME:CI_COMMIT_REF_NAME $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$IMAGE_NAME:latest
