FROM golang:1.25.0-alpine3.22@sha256:77dd832edf2752dafd030693bef196abb24dcba3a2bc3d7a6227a7a1dae73169 AS builder
ARG APP=/app
WORKDIR ${APP}

RUN apk add --no-cache make git
# disable cgo for go build
ENV CGO_ENABLED=0

COPY go.mod .
COPY go.sum .

RUN go mod download

# Copy the .git directory and restore the worktree, also handle current possible changes in go.mod and go.sum
COPY .git .git
RUN git restore --source=HEAD --worktree .
COPY go.mod .
COPY go.sum .

# Copy the necessary files for building and override the restored worktree
COPY Makefile .
COPY cmd .
COPY pkg .
COPY internal .

RUN make build-bots-linux-amd64

FROM alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
ARG APP=/app
ENV TZ=Etc/UTC \
    APP_USER=appuser

STOPSIGNAL SIGINT

RUN addgroup -S $APP_USER \
    && adduser -S $APP_USER -G $APP_USER

RUN apk add --no-cache bind-tools

USER $APP_USER
WORKDIR ${APP}
# Considered as a default HTTP API Port
EXPOSE 8080

COPY --from=builder ${APP}/build/linux-amd64/nodemon-discord ${APP}/nodemon-discord

ENTRYPOINT ["./nodemon-discord"]
