FROM golang:1.26rc3-alpine3.22@sha256:44671c30ff42221d26fa4f1e8d43d930f0ffe8def70ed90e1cf5af585bc4f38c AS builder
ARG APP=/app
WORKDIR ${APP}

RUN apk add --no-cache make git
# disable cgo for go build
ENV CGO_ENABLED=0

COPY go.mod .
COPY go.sum .

RUN go mod download

# Copy the .git directory and restore the worktree, also handle current possible changes in go.mod and go.sum
COPY .git .git
RUN git restore --source=HEAD --worktree .
COPY go.mod .
COPY go.sum .

# Copy the necessary files for building and override the restored worktree
COPY Makefile .
COPY cmd .
COPY pkg .
COPY internal .

RUN make build-bots-linux-amd64

FROM alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
ARG APP=/app
ENV TZ=Etc/UTC \
    APP_USER=appuser

STOPSIGNAL SIGINT

RUN addgroup -S $APP_USER \
    && adduser -S $APP_USER -G $APP_USER

RUN apk add --no-cache bind-tools

USER $APP_USER
WORKDIR ${APP}
# Considered as a default HTTP API Port
EXPOSE 8080

COPY --from=builder ${APP}/build/linux-amd64/nodemon-telegram ${APP}/nodemon-telegram

ENTRYPOINT ["./nodemon-telegram"]
